=== Rocachondo/Tarea3/tablanutricional.dtd
<!DOCTYPE tabla
[
<!ELEMENT tabla (alimento+)>
<!ELEMENT alimento (nombre,kcal,hc?,prot?,grasas?,categoria,tipo)>
<!ATTLIST alimento codigo NMTOKEN #REQUIRED>
<!ATTLIST alimento codigo ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT kcal (#PCDATA)>
<!ELEMENT hc (#PCDATA)>
<!ELEMENT prot (#PCDATA)>
<!ELEMENT grasas (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
]>

=== Rocachondo/Tarea3/tablanutricional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tabla SYSTEM "tablanutricional.dtd">
<tabla>
    <alimento codigo="1101">
        <nombre>Leche entera</nombre>
        <kcal>57</kcal>
        <hc>4.5</hc>
        <prot>3</prot>
        <grasas>3</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Leche</tipo>
    </alimento>
    <alimento codigo="1102">
        <nombre>Leche desnatada</nombre>
        <kcal>45</kcal>
        <hc>4.7</hc>
        <prot>3.1</prot>
        <grasas>1.5</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Leche</tipo>
    </alimento>
    <alimento codigo="1201">
        <nombre>Yogur con cereales</nombre>
        <kcal>48</kcal>
        <hc>9</hc>
        <prot>3</prot>
        <grasas>0.05</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Yogures</tipo>
    </alimento>
    <alimento codigo="1202">
        <nombre>Yogur con fibras y fruta</nombre>
        <kcal>71</kcal>
        <hc>12.5</hc>
        <prot>4.7</prot>
        <grasas>0.2</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Yogures</tipo>
    </alimento>
    <alimento codigo="1203">
        <nombre>Yogur desnatado saborizado</nombre>
        <kcal>34.5</kcal>
        <hc>4.4</hc>
        <prot>3.6</prot>
        <grasas>0.05</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Yogures</tipo>
    </alimento>
    <alimento codigo="1301">
        <nombre>Queso Philadelfia light</nombre>
        <kcal>200</kcal>
        <hc>6.6</hc>
        <prot>10</prot>
        <grasas>16.6</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Quesos</tipo>
    </alimento>
    <alimento codigo="1302">
        <nombre>Queso cottage</nombre>
        <kcal>95</kcal>
        <hc>2</hc>
        <prot>11.4</prot>
        <grasas>4.5</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Quesos</tipo>
    </alimento>
    <alimento codigo="1303">
        <nombre>Queso ricotta</nombre>
        <kcal>185</kcal>
        <hc>2.5</hc>
        <prot>14.5</prot>
        <grasas>13</grasas>
        <categoria>Lacteos</categoria>
        <tipo>Quesos</tipo>
    </alimento>
    <alimento codigo="2101">
        <nombre>Clara de huevo</nombre>
        <kcal>53</kcal>
        <hc>1</hc>
        <prot>11</prot>
        <grasas>0.2</grasas>
        <categoria>Huevos</categoria>
        <tipo>Huevos</tipo>
    </alimento>
    <alimento codigo="2102">
        <nombre>Huevo de codorniz</nombre>
        <kcal>179</kcal>
        <hc>3.6</hc>
        <prot>11.6</prot>
        <grasas>13.1</grasas>
        <categoria>Huevos</categoria>
        <tipo>Huevos</tipo>
    </alimento>
    <alimento codigo="3101">
        <nombre>Bife angosto</nombre>
        <kcal>182</kcal>
        <hc>0</hc>
        <prot>20.8</prot>
        <grasas>11.3</grasas>
        <categoria>Carnes</categoria>
        <tipo>Vacuno</tipo>
    </alimento>
    <alimento codigo="3102">
        <nombre>Lomo magro</nombre>
        <kcal>148</kcal>
        <hc>0</hc>
        <prot>20.7</prot>
        <grasas>6.5</grasas>
        <categoria>Carnes</categoria>
        <tipo>Vacuno</tipo>
    </alimento>
    <alimento codigo="3201">
        <nombre>Carne de cerdo magra</nombre>
        <kcal>276</kcal>
        <hc>0</hc>
        <prot>16.7</prot>
        <grasas>22.7</grasas>
        <categoria>Carnes</categoria>
        <tipo>Cerdo</tipo>
    </alimento>
    <alimento codigo="3501">
        <nombre>Jamón cocido</nombre>
        <kcal>126</kcal>
        <hc>3</hc>
        <prot>20</prot>
        <grasas>4</grasas>
        <categoria>Carnes</categoria>
        <tipo>Fiambre y embutido</tipo>
    </alimento>
    <alimento codigo="3502">
        <nombre>Lomo</nombre>
        <kcal>153</kcal>
        <hc>3</hc>
        <prot>23</prot>
        <grasas>5</grasas>
        <categoria>Carnes</categoria>
        <tipo>Fiambre y embutido</tipo>
    </alimento>
    <alimento codigo="3301">
        <nombre>Carne de pavo</nombre>
        <kcal>268</kcal>
        <hc>0.5</hc>
        <prot>20</prot>
        <grasas>20.1</grasas>
        <categoria>Carnes</categoria>
        <tipo>Ave</tipo>
    </alimento>
    <alimento codigo="3302">
        <nombre>Carne de pollo</nombre>
        <kcal>170</kcal>
        <hc>0</hc>
        <prot>18.2</prot>
        <grasas>10.2</grasas>
        <categoria>Carnes</categoria>
        <tipo>Ave</tipo>
    </alimento>
    <alimento codigo="4101">
        <nombre>Banana</nombre>
        <kcal>85</kcal>
        <hc>22.2</hc>
        <prot>1.1</prot>
        <grasas>0.2</grasas>
        <categoria>Frutas</categoria>
        <tipo>Fruta fresca</tipo>
    </alimento>
    <alimento codigo="4102">
        <nombre>Manzana</nombre>
        <kcal>58</kcal>
        <hc>15.2</hc>
        <prot>0.3</prot>
        <grasas>0.3</grasas>
        <categoria>Frutas</categoria>
        <tipo>Fruta fresca</tipo>
    </alimento>
    <alimento codigo="4201">
        <nombre>Almendra</nombre>
        <kcal>547</kcal>
        <hc>19.6</hc>
        <prot>18.6</prot>
        <grasas>54.1</grasas>
        <categoria>Frutas</categoria>
        <tipo>Frutos secos</tipo>
    </alimento>
    <alimento codigo="4202">
        <nombre>Nuez</nombre>
        <kcal>664</kcal>
        <hc>13.2</hc>
        <prot>13.7</prot>
        <grasas>67.2</grasas>
        <categoria>Frutas</categoria>
        <tipo>Frutos secos</tipo>
    </alimento>
    <alimento codigo="4301">
        <nombre>Ananá</nombre>
        <kcal>35</kcal>
        <hc>8.34</hc>
        <prot>0.38</prot>
        <grasas>0.12</grasas>
        <categoria>Frutas</categoria>
        <tipo>Fruta envasada</tipo>
    </alimento>
    <alimento codigo="5101">
        <nombre>Arroz blanco</nombre>
        <kcal>343</kcal>
        <hc>78.6</hc>
        <prot>6.7</prot>
        <grasas>0.25</grasas>
        <categoria>Cereales</categoria>
        <tipo>Cereal</tipo>
    </alimento>
    <alimento codigo="5102">
        <nombre>Avena arrollada</nombre>
        <kcal>387</kcal>
        <hc>62.5</hc>
        <prot>12.7</prot>
        <grasas>9.5</grasas>
        <categoria>Cereales</categoria>
        <tipo>Cereal</tipo>
    </alimento>
    <alimento codigo="5201">
        <nombre>Tallarines de huevo</nombre>
        <kcal>287</kcal>
        <hc>56.8</hc>
        <prot>9.2</prot>
        <grasas>2.6</grasas>
        <categoria>Cereales</categoria>
        <tipo>Pasta</tipo>
    </alimento>
    <alimento codigo="5202">
        <nombre>Fideos de harina integral</nombre>
        <kcal>359</kcal>
        <hc>70</hc>
        <prot>15.4</prot>
        <grasas>1.7</grasas>
        <categoria>Cereales</categoria>
        <tipo>Pasta</tipo>
    </alimento>
    <alimento codigo="5301">
        <nombre>Pan de centeno</nombre>
        <kcal>245</kcal>
        <hc>50.5</hc>
        <prot>8.2</prot>
        <grasas>1.1</grasas>
        <categoria>Cereales</categoria>
        <tipo>Pan</tipo>
    </alimento>
</tabla>
